# Generated by Django 5.0.2 on 2024-04-04 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='datetime',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='user',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='payment',
            new_name='payment_type',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='notes',
        ),
        migrations.AddField(
            model_name='expense',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expense',
            name='qty',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
