# Generated by Django 5.0.2 on 2024-05-02 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_rename_user_order_created_by_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='sales_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
